import { describe, it, expect, beforeAll, afterAll } from "bun:test";
import * as fs from "fs";
import { resolve, join } from "path";
import { bundleWidget } from "../bundler";

const TMP = "/tmp/readrun-widgets-e2e";
const WIDGETS_DIR = join(TMP, "widgets");
const TOOLKIT_ROOT = resolve(import.meta.dirname, "..");

beforeAll(() => {
  fs.mkdirSync(WIDGETS_DIR, { recursive: true });
  // A widget that imports a primitive — exercises the @readrun/widgets resolver.
  fs.writeFileSync(
    join(WIDGETS_DIR, "demo.tsx"),
    `import React from "react";
import { Slider } from "@readrun/widgets/primitives";

export function Demo() {
  return <Slider label="n" value={1} min={0} max={10} step={1} onChange={() => {}} />;
}
`
  );
  // A widget that goes deeper — @readrun/widgets/math/linalg.
  fs.writeFileSync(
    join(WIDGETS_DIR, "deep-import.tsx"),
    `import React from "react";
import { decompose } from "@readrun/widgets/math/linalg";

export function DeepImport() {
  const _r = decompose([[1, 0], [0, 1]]);
  return <div>{Object.keys(_r).length}</div>;
}
`
  );
});

afterAll(() => {
  try { fs.rmSync(TMP, { recursive: true, force: true }); } catch {}
});

describe("bundler end-to-end", () => {
  it("bundles a widget importing @readrun/widgets/primitives", async () => {
    const jsx = await bundleWidget("demo", { widgetsDir: WIDGETS_DIR, toolkitRoot: TOOLKIT_ROOT });
    expect(jsx).not.toMatch(/^import\s/m);
    expect(jsx).not.toMatch(/^export\s/m);
    expect(jsx.trimEnd()).toMatch(/render\(<Demo\s*\/>\);?$/m);
    expect(jsx).toMatch(/^\/\/ generated by @readrun\/widgets/m);
    expect(jsx).toMatch(
      /module\.exports = \{ Fragment: React\d*\.Fragment, jsx: jsx\d*, jsxs: jsx\d* \};/,
    );
    // The Slider implementation must have been inlined.
    expect(jsx).toContain("Slider");
  });

  it("resolves deep subpaths like @readrun/widgets/math/linalg", async () => {
    const jsx = await bundleWidget("deep-import", { widgetsDir: WIDGETS_DIR, toolkitRoot: TOOLKIT_ROOT });
    expect(jsx).not.toMatch(/^import\s/m);
    expect(jsx.trimEnd()).toMatch(/render\(<DeepImport\s*\/>\);?$/m);
    // decompose body must be present.
    expect(jsx).toContain("decompose");
  });

});
