import path from "node:path";
import { mkdir, readdir, stat } from "node:fs/promises";

import { bundleWidget } from "../../widgets/bundler.ts";

const GENERATED_WIDGET_BANNER = "// generated by @readrun/widgets";

export interface ContentWidgetsBuildResult {
	widgetsDir: string;
	outputDir: string;
	built: string[];
	unchanged: string[];
}

export interface BuildContentWidgetsOptions {
	toolkitRoot?: string;
}

export async function buildContentWidgets(
	contentDir: string,
	options: BuildContentWidgetsOptions = {},
): Promise<ContentWidgetsBuildResult> {
	const widgetsDir = path.join(contentDir, ".readrun", "widgets");
	const outputDir = path.join(contentDir, ".readrun", ".widgets-out");
	const toolkitRoot =
		options.toolkitRoot ?? path.resolve(import.meta.dirname, "../../widgets");
	const result: ContentWidgetsBuildResult = {
		widgetsDir,
		outputDir,
		built: [],
		unchanged: [],
	};

	if (!(await isDirectory(widgetsDir))) {
		return result;
	}

	const entries = (await readdir(widgetsDir))
		.filter((entry) => entry.endsWith(".tsx"))
		.sort();

	if (entries.length === 0) {
		return result;
	}

	await mkdir(outputDir, { recursive: true });

	for (const entry of entries) {
		const name = entry.slice(0, -".tsx".length);
		const outputPath = path.join(outputDir, `${name}.jsx`);
		const jsx = await bundleWidget(name, { widgetsDir, toolkitRoot });
		const previous = await readExistingGeneratedWidget(outputPath);

		if (previous && generatedWidgetBodiesMatch(previous, jsx)) {
			result.unchanged.push(outputPath);
			continue;
		}

		await Bun.write(outputPath, jsx);
		result.built.push(outputPath);
	}

	return result;
}

export function isWidgetSourceRelPath(relPath: string): boolean {
	return relPath === ".readrun/widgets" || relPath.startsWith(".readrun/widgets/");
}

async function isDirectory(pathArg: string): Promise<boolean> {
	try {
		return (await stat(pathArg)).isDirectory();
	} catch {
		return false;
	}
}

async function readExistingGeneratedWidget(
	outputPath: string,
): Promise<string | null> {
	const file = Bun.file(outputPath);
	if (!(await file.exists())) {
		return null;
	}

	const text = await file.text();
	if (!text.startsWith(GENERATED_WIDGET_BANNER)) {
		throw new Error(
			`Refusing to overwrite ${outputPath}; it is not generated by @readrun/widgets.`,
		);
	}
	return text;
}

function generatedWidgetBodiesMatch(left: string, right: string): boolean {
	return stripGeneratedWidgetBanner(left) === stripGeneratedWidgetBanner(right);
}

function stripGeneratedWidgetBanner(source: string): string {
	const lines = source.split("\n");
	if (lines[0]?.startsWith(GENERATED_WIDGET_BANNER)) {
		return lines.slice(2).join("\n");
	}
	return source;
}
