export const IMPORT_TO_PACKAGE: Record<string, string> = {
  PIL: "pillow",
  cv2: "opencv-python",
  sklearn: "scikit-learn",
  skimage: "scikit-image",
  bs4: "beautifulsoup4",
  yaml: "pyyaml",
  attr: "attrs",
  dotenv: "python-dotenv",
  gi: "pygobject",
  mapbox_earcut: "mapbox-earcut",
};

const STDLIB = new Set([
  "abc",
  "argparse",
  "array",
  "ast",
  "base64",
  "binascii",
  "bisect",
  "calendar",
  "codecs",
  "collections",
  "configparser",
  "contextlib",
  "copy",
  "csv",
  "ctypes",
  "dataclasses",
  "datetime",
  "decimal",
  "dis",
  "doctest",
  "email",
  "enum",
  "fnmatch",
  "fractions",
  "functools",
  "gc",
  "gettext",
  "glob",
  "gzip",
  "hashlib",
  "heapq",
  "html",
  "http",
  "importlib",
  "inspect",
  "io",
  "itertools",
  "json",
  "locale",
  "logging",
  "math",
  "multiprocessing",
  "numbers",
  "operator",
  "os",
  "pathlib",
  "pickle",
  "pkgutil",
  "platform",
  "pprint",
  "queue",
  "random",
  "re",
  "select",
  "shelve",
  "shutil",
  "signal",
  "socket",
  "sqlite3",
  "ssl",
  "statistics",
  "string",
  "struct",
  "subprocess",
  "sys",
  "sysconfig",
  "tarfile",
  "tempfile",
  "textwrap",
  "threading",
  "time",
  "traceback",
  "typing",
  "unicodedata",
  "unittest",
  "urllib",
  "warnings",
  "weakref",
  "xml",
  "zipfile",
]);

export function parsePythonImports(code: string): string[] {
  const packages = new Set<string>();
  const importPattern = /^\s*(?:import|from)\s+([A-Za-z_]\w*)/gm;
  let match: RegExpExecArray | null;

  while ((match = importPattern.exec(code)) !== null) {
    const moduleName = match[1]!;
    if (!STDLIB.has(moduleName)) {
      packages.add(IMPORT_TO_PACKAGE[moduleName] ?? moduleName);
    }
  }

  return [...packages].sort();
}
