import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { buildBanner, bundleWidget, kebabToPascal } from "./bundler.ts";

describe("kebabToPascal", () => {
	it("converts kebab-case names to PascalCase", () => {
		expect(kebabToPascal("distribution-explorer")).toBe(
			"DistributionExplorer",
		);
		expect(kebabToPascal("widget")).toBe("Widget");
		expect(kebabToPascal("a-b-c")).toBe("ABC");
	});
});

const tempRoot = mkdtempSync(path.join(tmpdir(), "readrun-widgets-test-"));
const widgetsDir = path.join(tempRoot, "widgets");
const toolkitRoot = path.resolve(import.meta.dirname);
const options = { widgetsDir, toolkitRoot };

beforeAll(() => {
	mkdirSync(widgetsDir, { recursive: true });
	writeFileSync(
		path.join(widgetsDir, "foo-bar.tsx"),
		`import React from "react";
export function FooBar() {
  return <div>hello {React.version}</div>;
}
`,
	);
	writeFileSync(
		path.join(widgetsDir, "named-const.tsx"),
		"export const NamedConst = () => <div>named const</div>;\n",
	);
	writeFileSync(
		path.join(widgetsDir, "default-ref.tsx"),
		"const DefaultRef = () => <div>default ref</div>;\nexport default DefaultRef;\n",
	);
	writeFileSync(
		path.join(widgetsDir, "wrong-name.tsx"),
		"export function NotWrongName() { return <div />; }\n",
	);
});

afterAll(() => {
	rmSync(tempRoot, { recursive: true, force: true });
});

describe("bundleWidget", () => {
	it("bundles a named component for the readrun JSX runtime", async () => {
		const result = await bundleWidget("foo-bar", options);

		expect(result).not.toMatch(/^import\s/m);
		expect(result).not.toMatch(/^export\s/m);
		expect(result).toMatch(/\bFooBar\b/);
		expect(result.trimEnd()).toMatch(/render\(<FooBar\s*\/>\);?$/m);
		expect(result).toMatch(/^\/\/ generated by @readrun\/widgets/m);
		expect(result).toContain("globalThis.React");
	});

	it("bundles a named const component", async () => {
		const result = await bundleWidget("named-const", options);

		expect(result).not.toMatch(/^export\s/m);
		expect(result.trimEnd()).toMatch(/render\(<NamedConst\s*\/>\);?$/m);
	});

	it("rejects a default-only component", async () => {
		await expect(bundleWidget("default-ref", options)).rejects.toThrow(
			/DefaultRef/,
		);
	});

	it("reports the expected name for a mismatched export", async () => {
		await expect(bundleWidget("wrong-name", options)).rejects.toThrow(
			/WrongName/,
		);
	});
});

describe("buildBanner", () => {
	it("contains the source path and a seven-character git SHA", () => {
		const banner = buildBanner("foo-bar", toolkitRoot);
		const lines = banner.split("\n").filter(Boolean);

		expect(lines[0]).toMatch(
			/\/\/ generated by @readrun\/widgets — edit \.readrun\/widgets\/foo-bar\.tsx/,
		);
		expect(lines[1]).toMatch(/\/\/ @readrun\/widgets@[0-9a-f]{7}/);
	});

	it("uses an unknown SHA outside a git checkout", () => {
		const banner = buildBanner(
			"any",
			path.join(toolkitRoot, "missing-toolkit-root"),
		);
		expect(banner).toContain("@readrun/widgets@unknown");
	});
});
