import { describe, it, expect, beforeAll } from "bun:test";
import * as fs from "fs";
import path from "node:path";
import {
	kebabToPascal,
	resolveWidgetExport,
	bundleWidget,
} from "./bundler";

// ─── 1. kebabToPascal ────────────────────────────────────────────────────────

describe("kebabToPascal", () => {
	it("converts multi-word kebab to PascalCase", () => {
		expect(kebabToPascal("distribution-explorer")).toBe("DistributionExplorer");
		expect(kebabToPascal("force-graph")).toBe("ForceGraph");
		expect(kebabToPascal("foo-bar-baz")).toBe("FooBarBaz");
	});

	it("converts single word (no dash)", () => {
		expect(kebabToPascal("widget")).toBe("Widget");
	});

	it("converts single-letter segments", () => {
		expect(kebabToPascal("a-b-c")).toBe("ABC");
	});
});

// ─── 2. resolveWidgetExport ─────────────────────────────────────────────────

describe("resolveWidgetExport", () => {
	it("finds named function exports", () => {
		const src = `export function FooBar() { return null; }`;
		expect(resolveWidgetExport(src, "FooBar")).toEqual({
			kind: "named",
			name: "FooBar",
		});
	});

	it("finds named const exports", () => {
		const src = `export const FooBar = () => null;`;
		expect(resolveWidgetExport(src, "FooBar")).toEqual({
			kind: "named",
			name: "FooBar",
		});
	});

	it("finds default function exports", () => {
		const src = `export default function FooBar() { return null; }`;
		expect(resolveWidgetExport(src, "FooBar")).toEqual({
			kind: "default",
			name: "FooBar",
		});
	});

	it("finds default identifier exports", () => {
		const src = `const FooBar = () => null;\nexport default FooBar;`;
		expect(resolveWidgetExport(src, "FooBar")).toEqual({
			kind: "default",
			name: "FooBar",
		});
	});

	it("finds named export lists", () => {
		const src = `const FooBar = () => null;\nexport {\n  FooBar\n};`;
		expect(resolveWidgetExport(src, "FooBar")).toEqual({
			kind: "named",
			name: "FooBar",
		});
	});

	it("finds export lists with default aliases", () => {
		const src = `function FooBar() { return null; }\nexport { FooBar as default };`;
		expect(resolveWidgetExport(src, "FooBar")).toEqual({
			kind: "default",
			name: "FooBar",
		});
	});

	it("rejects mismatched default exports", () => {
		const src = `export default function WrongName() { return null; }`;
		expect(resolveWidgetExport(src, "FooBar")).toBeNull();
	});

	it("rejects anonymous default exports", () => {
		const src = `export default () => null;`;
		expect(resolveWidgetExport(src, "FooBar")).toBeNull();
	});

	it("rejects renamed local exports", () => {
		const src = `function Internal() { return null; }\nexport { Internal as FooBar };`;
		expect(resolveWidgetExport(src, "FooBar")).toBeNull();
	});

	it("ignores type-only exports", () => {
		const src = `type FooBar = { value: number };\nexport type { FooBar };`;
		expect(resolveWidgetExport(src, "FooBar")).toBeNull();
	});
});

// ─── 3. bundleWidget integration ────────────────────────────────────────────

const TMP_DIR = "/tmp/widgets-test";
const WIDGETS_DIR = `${TMP_DIR}/widgets`;
const OUT_DIR = `${TMP_DIR}/out`;

beforeAll(() => {
	fs.mkdirSync(WIDGETS_DIR, { recursive: true });
	fs.mkdirSync(OUT_DIR, { recursive: true });

	fs.writeFileSync(
		`${WIDGETS_DIR}/foo-bar.tsx`,
		`import React from "react";\n\nexport default function FooBar() {\n  return <div>hello {React.version}</div>;\n}\n`,
	);
	fs.writeFileSync(
		`${WIDGETS_DIR}/default-ref.tsx`,
		`const DefaultRef = () => <div>default ref</div>;\nexport default DefaultRef;\n`,
	);
	fs.writeFileSync(
		`${WIDGETS_DIR}/named-const.tsx`,
		`export const NamedConst = () => <div>named const</div>;\n`,
	);
	fs.writeFileSync(
		`${WIDGETS_DIR}/wrong-name.tsx`,
		`export default function NotWrongName() {\n  return <div />;\n}\n`,
	);
});

const TOOLKIT_ROOT = path.resolve(import.meta.dirname);

describe("bundleWidget integration", () => {
	it("produces output with correct shape", async () => {
		const result = await bundleWidget("foo-bar", {
			widgetsDir: WIDGETS_DIR,
			toolkitRoot: TOOLKIT_ROOT,
		});

		// No import statements
		expect(result).not.toMatch(/^import\s/m);

		// No export statements
		expect(result).not.toMatch(/^export\s/m);

		// Contains the component name
		expect(result).toMatch(/\bFooBar\b/);

		// Ends with render call
		expect(result.trimEnd()).toMatch(/render\(<FooBar\s*\/>\);?$/m);

		// Starts with the banner
		expect(result).toMatch(/^\/\/ generated by @readrun\/widgets/m);

		// References globalThis.React somewhere
		expect(result).toContain("globalThis.React");
	});

	it("supports default identifier exports while rendering the file PascalName", async () => {
		const result = await bundleWidget("default-ref", {
			widgetsDir: WIDGETS_DIR,
			toolkitRoot: TOOLKIT_ROOT,
		});

		expect(result).not.toMatch(/^export\s/m);
		expect(result.trimEnd()).toMatch(/render\(<DefaultRef\s*\/>\);?$/m);
	});

	it("supports named const component exports", async () => {
		const result = await bundleWidget("named-const", {
			widgetsDir: WIDGETS_DIR,
			toolkitRoot: TOOLKIT_ROOT,
		});

		expect(result).not.toMatch(/^export\s/m);
		expect(result.trimEnd()).toMatch(/render\(<NamedConst\s*\/>\);?$/m);
	});

	it("reports a clear error for mismatched component names", async () => {
		await expect(
			bundleWidget("wrong-name", {
				widgetsDir: WIDGETS_DIR,
				toolkitRoot: TOOLKIT_ROOT,
			}),
		).rejects.toThrow(/expected "WrongName"|named "WrongName"/i);
	});
});

// ─── 4. Banner format ────────────────────────────────────────────────────────

import { buildBanner } from "./bundler";

describe("buildBanner", () => {
	it("contains two lines with the correct structure", () => {
		const banner = buildBanner("foo-bar", TOOLKIT_ROOT);
		const lines = banner.split("\n").filter(Boolean);

		expect(lines[0]).toMatch(
			/\/\/ generated by @readrun\/widgets — edit \.readrun\/widgets\/foo-bar\.tsx/,
		);
		expect(lines[1]).toMatch(/\/\/ @readrun\/widgets@[0-9a-f]{7}/);
	});

	it("SHA is 7 hex characters", () => {
		const banner = buildBanner("any", TOOLKIT_ROOT);
		const match = banner.match(/@readrun\/widgets@([0-9a-f]+)/);
		expect(match).not.toBeNull();
		expect(match![1]).toHaveLength(7);
	});
});
