/**
 * Bundle content widgets into JSX payloads for readrun's browser runtime.
 */

import type { BunPlugin } from "bun";
import path from "node:path";

export function kebabToPascal(name: string): string {
	return name
		.split("-")
		.map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
		.join("");
}

/** Keep React supplied by readrun's JSX runtime out of widget bundles. */
export const reactGlobalsPlugin: BunPlugin = {
	name: "react-globals",
	setup(build) {
		build.onResolve({ filter: /^react$/ }, () => ({
			path: "react",
			namespace: "globals",
		}));
		build.onResolve({ filter: /^react-dom$/ }, () => ({
			path: "react-dom",
			namespace: "globals",
		}));
		build.onResolve({ filter: /^react\/jsx-runtime$/ }, () => ({
			path: "react/jsx-runtime",
			namespace: "globals",
		}));
		build.onLoad({ filter: /.*/, namespace: "globals" }, (args) => ({
			contents:
				args.path === "react"
					? "module.exports = globalThis.React;"
					: args.path === "react-dom"
						? "module.exports = globalThis.ReactDOM;"
						: [
								"const React = globalThis.React;",
								"function jsx(type, props, key) {",
								"  const nextProps = key === undefined ? props : Object.assign({}, props, { key });",
								"  return React.createElement(type, nextProps);",
								"}",
								"module.exports = { Fragment: React.Fragment, jsx, jsxs: jsx };",
							].join("\n"),
			loader: "js",
		}));
	},
};

const widgetSubpackages = [
	"primitives",
	"plot",
	"diagram",
	"interaction",
	"draw",
	"math",
];

/** Resolve the public @readrun/widgets name to the in-repo toolkit. */
export function readrunWidgetsPlugin(toolkitRoot: string): BunPlugin {
	return {
		name: "readrun-widgets",
		setup(build) {
			build.onResolve(
				{ filter: /^@readrun\/widgets(\/.*)?$/ },
				async (args) => {
					const specifier = args.path;
					if (specifier === "@readrun/widgets") {
						return { path: path.join(toolkitRoot, "index.ts") };
					}

					const rest = specifier.slice("@readrun/widgets/".length);
					const [head, ...tail] = rest.split("/");
					if (!head || !widgetSubpackages.includes(head)) {
						throw new Error(
							`Unknown @readrun/widgets subpath: "${specifier}". Valid roots: ${widgetSubpackages.map((name) => `@readrun/widgets/${name}`).join(", ")}`,
						);
					}

					const base = path.join(toolkitRoot, head, ...tail);
					const candidates =
						tail.length === 0
							? [path.join(base, "index.tsx"), path.join(base, "index.ts")]
							: [
									`${base}.tsx`,
									`${base}.ts`,
									path.join(base, "index.tsx"),
									path.join(base, "index.ts"),
								];
					for (const candidate of candidates) {
						if (await Bun.file(candidate).exists()) return { path: candidate };
					}

					throw new Error(
						`Cannot resolve "${specifier}" — tried ${candidates.join(", ")}`,
					);
				},
			);
		},
	};
}

export function buildBanner(widgetName: string, toolkitRoot: string): string {
	let sha = "unknown";
	const result = Bun.spawnSync(
		["git", "-C", toolkitRoot, "rev-parse", "--short", "HEAD"],
		{ stderr: "ignore" },
	);
	if (result.success) sha = result.stdout.toString().trim();

	const timestamp = new Date().toISOString().replace(/\.\d{3}Z$/, "Z");
	return (
		`// generated by @readrun/widgets — edit .readrun/widgets/${widgetName}.tsx, then re-run rr\n` +
		`// @readrun/widgets@${sha} — generated ${timestamp}\n`
	);
}

const widgetRenderSentinel = "__readrunWidgetRender";

function buildRenderEntrySource(name: string, pascalName: string): string {
	return (
		`import { ${pascalName} } from ${JSON.stringify(`./${name}.tsx`)};\n` +
		`${widgetRenderSentinel}(${pascalName});\n`
	);
}

function replaceRenderSentinel(source: string, pascalName: string): string {
	const sentinelCall = new RegExp(
		`(^|\\n)${widgetRenderSentinel}\\([A-Za-z_$][A-Za-z0-9_$]*\\);(?=\\n|$)`,
	);
	if (!sentinelCall.test(source)) {
		throw new Error(
			`Bun build output for widget "${pascalName}" did not contain the generated render sentinel`,
		);
	}
	return source.replace(sentinelCall, `$1render(<${pascalName} />);\n`);
}

export interface BundleWidgetOpts {
	/** Absolute path to the directory containing <name>.tsx files. */
	widgetsDir: string;
	/** Absolute path to readrun/src/widgets/. */
	toolkitRoot: string;
}

export async function bundleWidget(
	name: string,
	opts: BundleWidgetOpts,
): Promise<string> {
	const { widgetsDir, toolkitRoot } = opts;
	const sourcePath = path.join(widgetsDir, `${name}.tsx`);
	if (!(await Bun.file(sourcePath).exists())) {
		throw new Error(`Widget not found: ${sourcePath}`);
	}

	const pascalName = kebabToPascal(name);
	const virtualEntryPath = path.join(widgetsDir, `${name}.readrun-entry.tsx`);
	const result = await Bun.build({
		entrypoints: [virtualEntryPath],
		files: {
			[virtualEntryPath]: buildRenderEntrySource(name, pascalName),
		},
		format: "esm",
		target: "browser",
		jsx: {
			runtime: "classic",
			factory: "React.createElement",
			fragment: "React.Fragment",
		},
		plugins: [reactGlobalsPlugin, readrunWidgetsPlugin(toolkitRoot)],
		throw: false,
	});

	if (!result.success) {
		const diagnostics = result.logs.map(String).join("\n");
		throw new Error(`Failed to bundle widget "${name}":\n${diagnostics}`);
	}

	const output = result.outputs[0];
	if (!output) throw new Error(`Bun produced no output for widget "${name}"`);
	const source = await output.text();
	return buildBanner(name, toolkitRoot) + replaceRenderSentinel(source, pascalName);
}
